### ISSUE TITLE
CruiseControl breaks if cluster name is not kafka

### ISSUE THREAD

**Issue by stephen-dahl** [banzaicloud/kafka-operator#67]
CruiseControl is hardcoded to connect to kafka-headless.

**Steps to reproduce the issue:**
create a cluster as described in readme but change the KafkaCluster metadata.name to dev

**Expected behavior**
CruiseControl connects to dev-headless

```
78     [           main] WARN  ache.kafka.clients.ClientUtils  - Removing server kafka-headless:29092 from bootstrap.servers as DNS resolution failed for kafka-headless
Exception in thread "main" org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:66)
	at com.linkedin.kafka.cruisecontrol.common.MetadataClient.<init>(MetadataClient.java:46)
	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.<init>(LoadMonitor.java:116)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:108)
	at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:70)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:71)
```

**Comment by baluchicken** [comment]
Thanks for the issue, will fix this soon and release a new version.

**Comment by baluchicken** [comment]
@stephen-dahl we just released a new version of the Operator which fixes this.
https://github.com/banzaicloud/kafka-operator/releases/tag/0.3.2
